name: birthday_gift
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+14

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^7.1.0
  flutter_contacts: ^1.1.6
  flutter_local_notifications: ^12.0.2
  workmanager: ^0.5.0
  flutter_keyboard_visibility: ^5.4.0
  device_info_plus: ^6.0.0
  package_info_plus: ^2.0.0
  webview_flutter: ^4.0.0

  url_launcher: ^6.1.6
  collection: ^1.16.0
  shared_preferences: ^2.0.15
  result_type: ^0.1.0

  # UI
  syncfusion_flutter_datepicker: ^20.4.54
  flutter_svg: ^1.0.0
  cupertino_icons: ^1.0.5
  mask_text_input_formatter: ^2.4.0
  country_picker: ^2.0.16

  # Firebase
  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.7
  firebase_auth: ^4.2.1
  firebase_crashlytics: ^3.0.7
  cloud_firestore: ^4.2.0

dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/ic_launcher.png"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"
  adaptive_icon_background: "assets/icon/ic_launcher_background.png"

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/icon/MyFlutterApp.ttf
    - family: SFProText
      fonts:
        - asset: assets/font/SF-Pro-Text-Regular.otf
        - asset: assets/font/SF-Pro-Text-Semibold.otf
          weight: 600
