name: birthday_gift
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.1.3
  equatable: ^2.0.3
  dartz: ^0.9.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_bloc: ^7.1.0
  contacts_service: ^0.6.1
  flutter_local_notifications: ^8.1.1+2
  workmanager: ^0.5.0-dev.7

  # UI
  syncfusion_flutter_datepicker: ^19.2.57
  flutter_svg: ^1.0.0
  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.0.0

  # Firebase
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.1.1
  cloud_firestore: ^2.5.3

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/icon/MyFlutterApp.ttf
    - family: SFProText
      fonts:
        - asset: assets/font/SFProText-Regular.ttf